medical_terms = {
    "Hemograma": ["Hemograma", "Hemograma completo", "Hemograma total", "CBC", "Complete Blood Count"],
    "Glicemia": ["Glicose em jejum", "Glicemia de jejum", "Glicemia basal", "Glicose plasmática em jejum", "Glucose fasting"],
    "Hemoglobina": ["HbA1c", "Hemoglobina glicada", "Hemoglobina glicada A1c", "A1c", "Glycated hemoglobin"],
    "HOMA-IR": ["HOMA-IR", "HOMA índice de resistência à insulina", "Homeostatic Model Assessment for Insulin Resistance", "HOMA-IR index"],
    "HOMA-β": ["HOMA-β", "HOMA beta", "HOMA função das células beta", "Homeostatic Model Assessment for Beta-cell Function"],
    "Insulina": ["Insulina", "Insulina basal", "Insulina plasmática", "Insulina sérica", "Fasting insulin"],
    "TSH": ["TSH", "Hormônio estimulante da tireoide", "TSH ultra-sensível", "TSHus", "Thyroid stimulating hormone"],
    "T3L": ["T3 livre", "Triiodotironina livre", "FT3", "T3L", "Free T3"],
    "T4L": ["T4 livre", "Tiroxina livre", "FT4", "T4L", "Free T4"],
    "Testosterona livre": ["Testosterona livre", "Testosterona livre calculada", "Testosterona biodisponível", "Free testosterone (calc)", "Testosterona calculada"],
    "Testosterona total": ["Testosterona total", "Testosterona sérica total", "Testosterone total", "Total testosterone"],
    "Progesterona": ["Progesterona", "Progesterona sérica", "Serum progesterone"],
    "Estradiol": ["Estradiol", "E2", "17β-estradiol", "Estradiol sérico", "Estradiol 17-beta"],
    "DHT": ["Dihidrotestosterona", "DHT", "5α-dihidrotestosterona", "Dihydrotestosterone"],
    "LH": ["LH", "Hormônio luteinizante", "Luteinizing hormone"],
    "FSH": ["FSH", "Hormônio folículo-estimulante", "Follicle stimulating hormone"],
    "Colesterol total": ["Colesterol total", "Colesterol sérico total", "Total cholesterol"],
    "HDL": ["HDL", "Colesterol HDL", "HDL cholesterol", "Lipoproteína de alta densidade"],
    "LDL": ["LDL", "Colesterol LDL", "LDL cholesterol", "Lipoproteína de baixa densidade"],
    "VLDL": ["VLDL", "Colesterol VLDL", "VLDL cholesterol", "Lipoproteína de muito baixa densidade"],
    "Triglicerídeos": ["Triglicerídeos", "Triglicérides", "TG", "Triglycerides"],
    "TGO": ["TGO", "AST", "Transaminase oxalacética", "Aspartato aminotransferase"],
    "TGP": ["TGP", "ALT", "Transaminase pirúvica", "Alanina aminotransferase"],
    "Cortisol matinal": ["Cortisol matinal", "Cortisol sérico", "Cortisol basal", "Morning cortisol"],
    "Gama-GT": ["Gama-GT", "GGT", "Gamma-glutamiltransferase", "Gamma GT"],
    "Vitamina D total": ["25-hidroxivitamina D", "25-OH vitamina D", "Vitamina D total", "25-hydroxyvitamin D"],
    "Creatinina": ["Creatinina", "Creatinina sérica", "Serum creatinine"],
    "Ureia": ["Ureia", "Nitrogênio ureico", "BUN", "Blood urea nitrogen"],
    "Fibrinogênio": ["Fibrinogênio", "Fibrinogênio plasmático", "Plasma fibrinogen"],
    "Ferritina": ["Ferritina", "Ferritina sérica", "Serum ferritin"],
    "Ferro": ["Ferro", "Ferro sérico", "Fe sérico", "Serum iron"],
    "SHBG": ["SHBG", "Globulina ligadora de hormônios sexuais", "Sex hormone binding globulin", "Globulina ligadora de esteróides sexuais"],
    "Paratormônio": ["Paratormônio", "PTH intacto", "Hormônio da paratireoide", "Parathyroid hormone"],
    "Lipoproteína(a)": ["Lipoproteína(a)", "Lp(a)", "Lipoprotein(a)"],
    "Vitamina B12": ["Vitamina B12", "Cobalamina", "Vitamin B12"],
    "Vitamina B6": ["Vitamina B6", "Piridoxina", "Vitamin B6"],
    "Vitamina B9": ["Vitamina B9", "Ácido fólico", "Folato", "Folate"],
    "Homocisteína": ["Homocisteína", "Homocisteína plasmática", "Plasma homocysteine"],
    "Apo A1": ["Apo A1", "Apolipoproteína A-I", "Apolipoprotein A1"],
    "Apo B": ["Apo B", "Apolipoproteína B", "Apolipoprotein B"],
    "Ácido úrico": ["Ácido úrico", "Urato", "Uric acid"],
    "Sódio": ["Sódio", "Na+", "Sódio sérico", "Serum sodium"],
    "Potássio": ["Potássio", "K+", "Potássio sérico", "Serum potassium"],
    "PCR": ["PCR", "Proteína C reativa", "PCR ultrassensível", "hs-CRP", "High sensitivity C-reactive protein"],
    }